//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeaconUserDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BeaconUserDetail()
        {
            this.BeaconScores = new HashSet<BeaconScore>();
        }
    
        public int BeaconId { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string Mobile { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string PermanentAddress { get; set; }
        public string HomeTown { get; set; }
        public string PostalCode { get; set; }
        public int Country { get; set; }
        public string PreviousExperience { get; set; }
        public int JobHops { get; set; }
        public string SpecialTags { get; set; }
        public string PreferedLocation { get; set; }
        public string QueryStringFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BeaconScore> BeaconScores { get; set; }
    }
}
