//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeaconVacancy
    {
        public int VacancyID { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public string VacancyStatus { get; set; }
        public string VacancyTitle { get; set; }
        public string VacancyDescription { get; set; }
        public string Salary { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string VacancyRole { get; set; }
        public Nullable<int> DeptID { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
