//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeaconUserVacancyAdditionalInfo
    {
        public int BeaconID { get; set; }
        public int VacancyID { get; set; }
        public string SelectionQ1 { get; set; }
        public string AnswerSelectionQ1 { get; set; }
        public string SelectionQ2 { get; set; }
        public string AnswerSelectionQ2 { get; set; }
        public string SelectionQ3 { get; set; }
        public string AnswerSelectionQ3 { get; set; }
        public string KillerQ1 { get; set; }
        public string AnswerKillerQ1 { get; set; }
        public string KillerQ2 { get; set; }
        public string AnswerKillerQ2 { get; set; }
        public string KillerQ3 { get; set; }
        public string AnswerKillerQ3 { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> AppStatusId { get; set; }
        public Nullable<bool> CountryEligibility { get; set; }
        public Nullable<bool> CriminalCharge { get; set; }
        public string Source { get; set; }
    }
}
