//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeaconGPITM
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public string ITM { get; set; }
        public string PrimaryOrSecondary { get; set; }
        public string ISV { get; set; }
        public string Client { get; set; }
        public string Notes { get; set; }
        public int Status { get; set; }
    
        public virtual BeaconGPEmployeePersonalDetail BeaconGPEmployeePersonalDetail { get; set; }
    }
}
