//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeaconGPEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BeaconGPEmployee()
        {
            this.BeaconGPEmployeeEducationDetails = new HashSet<BeaconGPEmployeeEducationDetail>();
            this.BeaconGPEmployeeWorkExperiences = new HashSet<BeaconGPEmployeeWorkExperience>();
        }
    
        public int EmployeeId { get; set; }
        public Nullable<int> BeaconId { get; set; }
        public Nullable<int> DirectManagerEmployeeId { get; set; }
        public Nullable<int> MatrixManagerEmployeeId { get; set; }
        public System.DateTime HireDate { get; set; }
        public Nullable<int> Division { get; set; }
        public string Department { get; set; }
        public Nullable<int> JobTitle { get; set; }
        public string JobTitle2 { get; set; }
        public int Location { get; set; }
        public string Sublocation { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public int PayrollId { get; set; }
        public string JobtitleDescription { get; set; }
        public string TradingSystem { get; set; }
    
        public virtual BeaconGPDepartment BeaconGPDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BeaconGPEmployeeEducationDetail> BeaconGPEmployeeEducationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BeaconGPEmployeeWorkExperience> BeaconGPEmployeeWorkExperiences { get; set; }
    }
}
