//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeaconPermission
    {
        public int Id { get; set; }
        public int PermissionsId { get; set; }
        public string Permissions_Desc { get; set; }
        public string Permission_Display { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<bool> isMasterTable { get; set; }
        public Nullable<int> MasterTableId { get; set; }
    }
}
