//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeaconUserStatu
    {
        public int BeaconId { get; set; }
        public string CandidateStatus { get; set; }
        public string OfferLetterStatus { get; set; }
        public string AllocatedLocation { get; set; }
        public Nullable<System.DateTime> ExpectedDateOfJoining { get; set; }
        public string ReferredBy { get; set; }
        public string SourceOfRecruitment { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<System.DateTime> DateOfRegistration { get; set; }
    }
}
