//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeaconUserEducationDetail
    {
        public int BeaconId { get; set; }
        public string Standard { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public string YearOfCompletion { get; set; }
        public string Comments { get; set; }
        public string Specialization { get; set; }
        public string College { get; set; }
        public string CountryOfStudy { get; set; }
        public string Degree { get; set; }
    }
}
