//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeaconGPEmployeeEducationDetail
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public string Degree { get; set; }
        public string School { get; set; }
        public string YearOfPassing { get; set; }
        public decimal CgpaORPercent { get; set; }
        public string standard { get; set; }
        public string Specialization { get; set; }
        public string CountryOfStudy { get; set; }
    
        public virtual BeaconGPEmployee BeaconGPEmployee { get; set; }
    }
}
