//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeaconGPTerminationDetail
    {
        public int EmployeeId { get; set; }
        public Nullable<System.DateTime> DateOfResignation { get; set; }
        public Nullable<int> ReasonForLeavingId { get; set; }
        public Nullable<System.DateTime> LastDayWorked { get; set; }
        public Nullable<int> ResignationType { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual BeaconGPReasonForLeaving BeaconGPReasonForLeaving { get; set; }
    }
}
