//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompleteResultSet
    {
        public int TestId { get; set; }
        public string TestAuthor { get; set; }
        public string QTIKey { get; set; }
        public string NumOfAttempt { get; set; }
        public string CompletionStatus { get; set; }
        public Nullable<decimal> Score { get; set; }
        public string Response { get; set; }
        public string Duration { get; set; }
        public string TestLabel { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> OrderId { get; set; }
    }
}
