//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BeaconScore> BeaconScores { get; set; }
        public virtual DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public virtual DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public virtual DbSet<aspnet_Paths> aspnet_Paths { get; set; }
        public virtual DbSet<aspnet_PersonalizationAllUsers> aspnet_PersonalizationAllUsers { get; set; }
        public virtual DbSet<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
        public virtual DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public virtual DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public virtual DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
        public virtual DbSet<aspnet_WebEvent_Events> aspnet_WebEvent_Events { get; set; }
        public virtual DbSet<BeaconAppStatu> BeaconAppStatus { get; set; }
        public virtual DbSet<BeaconCollege> BeaconColleges { get; set; }
        public virtual DbSet<BeaconCountry> BeaconCountries { get; set; }
        public virtual DbSet<BeaconCountryOfStudy> BeaconCountryOfStudies { get; set; }
        public virtual DbSet<BeaconDegree> BeaconDegrees { get; set; }
        public virtual DbSet<BeaconDepartment> BeaconDepartments { get; set; }
        public virtual DbSet<BeaconGPDepartment> BeaconGPDepartments { get; set; }
        public virtual DbSet<BeaconGPDivision> BeaconGPDivisions { get; set; }
        public virtual DbSet<BeaconGPEmployee> BeaconGPEmployees { get; set; }
        public virtual DbSet<BeaconGPEmployeeChildrenDetail> BeaconGPEmployeeChildrenDetails { get; set; }
        public virtual DbSet<BeaconGPEmployeeEducationDetail> BeaconGPEmployeeEducationDetails { get; set; }
        public virtual DbSet<BeaconGPEmployeePersonalDetail> BeaconGPEmployeePersonalDetails { get; set; }
        public virtual DbSet<BeaconGPEmployeeProduct> BeaconGPEmployeeProducts { get; set; }
        public virtual DbSet<BeaconGPEmployeeWorkExperience> BeaconGPEmployeeWorkExperiences { get; set; }
        public virtual DbSet<BeaconGPExitInterview> BeaconGPExitInterviews { get; set; }
        public virtual DbSet<BeaconGPExitQuestion> BeaconGPExitQuestions { get; set; }
        public virtual DbSet<BeaconGPITM> BeaconGPITMs { get; set; }
        public virtual DbSet<BeaconGPJobTitle> BeaconGPJobTitles { get; set; }
        public virtual DbSet<BeaconGPManager> BeaconGPManagers { get; set; }
        public virtual DbSet<BeaconGPProduct> BeaconGPProducts { get; set; }
        public virtual DbSet<BeaconGPReasonForLeaving> BeaconGPReasonForLeavings { get; set; }
        public virtual DbSet<BeaconGPResignationType> BeaconGPResignationTypes { get; set; }
        public virtual DbSet<BeaconGPStatu> BeaconGPStatus { get; set; }
        public virtual DbSet<BeaconGPTerminationDetail> BeaconGPTerminationDetails { get; set; }
        public virtual DbSet<BeaconLocation> BeaconLocations { get; set; }
        public virtual DbSet<BeaconPermission> BeaconPermissions { get; set; }
        public virtual DbSet<BeaconUserDetail> BeaconUserDetails { get; set; }
        public virtual DbSet<BeaconUserEducationDetail> BeaconUserEducationDetails { get; set; }
        public virtual DbSet<BeaconUserStatu> BeaconUserStatus { get; set; }
        public virtual DbSet<BeaconUserWorkExperience> BeaconUserWorkExperiences { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Roles_Department_Mapping> Roles_Department_Mapping { get; set; }
        public virtual DbSet<Roles_Locations_Mapping> Roles_Locations_Mapping { get; set; }
        public virtual DbSet<Roles_Permissions_Mapping> Roles_Permissions_Mapping { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<BeaconCandidateStatusList> BeaconCandidateStatusLists { get; set; }
        public virtual DbSet<BeaconGPHRLocationMapping> BeaconGPHRLocationMappings { get; set; }
        public virtual DbSet<BeaconHROM> BeaconHROMs { get; set; }
        public virtual DbSet<BeaconOfferLetterStatu> BeaconOfferLetterStatus { get; set; }
        public virtual DbSet<BeaconSourceOfRecruitment> BeaconSourceOfRecruitments { get; set; }
        public virtual DbSet<BeaconUserVacancyAdditionalInfo> BeaconUserVacancyAdditionalInfoes { get; set; }
        public virtual DbSet<BeaconVacancy> BeaconVacancies { get; set; }
        public virtual DbSet<BeaconVacancyInfoSource> BeaconVacancyInfoSources { get; set; }
        public virtual DbSet<CompleteResultSet> CompleteResultSets { get; set; }
        public virtual DbSet<CompleteResultSetArchive> CompleteResultSetArchives { get; set; }
        public virtual DbSet<TAOMasterData> TAOMasterDatas { get; set; }
    }
}
