//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAOMasterData
    {
        public string Label { get; set; }
        public decimal Score { get; set; }
        public decimal LowLevel { get; set; }
        public decimal HighLevel { get; set; }
        public Nullable<decimal> TimeLimits { get; set; }
    }
}
